modLoader="javafml"
loaderVersion="[42,)"
license="All rights reserved"
[[mods]]
modId="l2weaponry"
version="${file.jarVersion}" #mandatory
displayName="L2 Weaponry" #mandatory
logoFile="l2weaponry.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
'''
[[dependencies.l2weaponry]]
    modId="forge"
    mandatory=true
    versionRange="[42.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2weaponry]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.l2weaponry]]
    modId="l2library"
    mandatory=true
    versionRange="[1.8.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2weaponry]]
    modId="l2complements"
    mandatory=true
    versionRange="[1.0.6,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.l2weaponry]]
    modId="modulargolems"
    mandatory=false
    versionRange="[1.7.5,)"
    ordering="AFTER"
    side="BOTH"